import type { Express } from 'express';
import { publicGames } from '../games/public-games.js';
import { readSession } from './auth.js';
import { prisma } from './prisma.js';

type StoredResult = { winner?: string; draw?: boolean };
type Stat = { gameId: string; played: number; won: number; lost: number; draws: number };
const gameIds = publicGames.map((game) => game.id);
function parseResult(value: string): StoredResult { try { return JSON.parse(value) as StoredResult; } catch { return {}; } }
function fullStats(stats: Stat[]) { return gameIds.map((gameId) => { const found = stats.find((stat) => stat.gameId === gameId); const value = found ?? { gameId, played: 0, won: 0, lost: 0, draws: 0 }; return { ...value, winRate: value.played ? Math.round(value.won / value.played * 100) : 0 }; }); }
function totals(stats: Stat[]) { const total = stats.reduce((sum, stat) => ({ played: sum.played + stat.played, won: sum.won + stat.won, lost: sum.lost + stat.lost, draws: sum.draws + stat.draws }), { played: 0, won: 0, lost: 0, draws: 0 }); return { ...total, winRate: total.played ? Math.round(total.won / total.played * 100) : 0, points: total.won * 3 + total.draws }; }
function recentMatches(players: Array<{ playerId: string; playerName: string; score: number; placement: number | null; match: { id: string; gameId: string; endedAt: Date; resultJson: string } }>) { return players.map((player) => { const result = parseResult(player.match.resultJson); return { id: player.match.id, gameId: player.match.gameId, playerName: player.playerName, score: player.score, placement: player.placement, outcome: result.draw ? 'draw' : result.winner === player.playerId ? 'win' : 'loss', endedAt: player.match.endedAt }; }); }
const userSelect = { id: true, displayName: true, avatarUrl: true, createdAt: true, stats: { select: { gameId: true, played: true, won: true, lost: true, draws: true } }, matchPlayers: { take: 10, orderBy: { match: { endedAt: 'desc' as const } }, select: { playerId: true, playerName: true, score: true, placement: true, match: { select: { id: true, gameId: true, endedAt: true, resultJson: true } } } } } as const;

export function configureApi(app: Express): void {
  app.get('/api/profile', async (request, response, next) => { try { const session = await readSession(request); if (!session) return void response.status(401).json({ error: 'Sign in to view your profile' }); const user = await prisma.user.findUnique({ where: { id: session.userId }, select: { ...userSelect, email: true } }); if (!user) return void response.status(404).json({ error: 'Profile not found' }); response.set('Cache-Control', 'private, no-store'); response.json({ profile: { id: user.id, displayName: user.displayName, email: user.email, avatarUrl: user.avatarUrl, memberSince: user.createdAt }, totals: totals(user.stats), byGame: fullStats(user.stats), recentMatches: recentMatches(user.matchPlayers) }); } catch (error) { next(error); } });

  app.get('/api/players/:playerId', async (request, response, next) => { try { const user = await prisma.user.findUnique({ where: { id: request.params.playerId }, select: userSelect }); if (!user) return void response.status(404).json({ error: 'Player not found' }); response.set('Cache-Control', 'public, max-age=30'); response.json({ profile: { id: user.id, displayName: user.displayName, avatarUrl: user.avatarUrl, memberSince: user.createdAt }, totals: totals(user.stats), byGame: fullStats(user.stats), recentMatches: recentMatches(user.matchPlayers) }); } catch (error) { next(error); } });

  app.get('/api/leaderboard', async (request, response, next) => { try { const scope = typeof request.query.game === 'string' ? request.query.game : 'all'; if (scope !== 'all' && !gameIds.includes(scope as typeof gameIds[number])) return void response.status(400).json({ error: 'Unknown game' }); const users = await prisma.user.findMany({ select: { id: true, displayName: true, avatarUrl: true, createdAt: true, stats: { select: { gameId: true, played: true, won: true, lost: true, draws: true } } } }); const ranked = users.map((user) => { const selected = scope === 'all' ? user.stats : user.stats.filter((stat) => stat.gameId === scope); return { id: user.id, displayName: user.displayName, avatarUrl: user.avatarUrl, memberSince: user.createdAt, ...totals(selected) }; }).sort((a, b) => b.points - a.points || b.won - a.won || b.winRate - a.winRate || b.played - a.played || a.displayName.localeCompare(b.displayName)).map((player, index) => ({ rank: index + 1, ...player })); response.set('Cache-Control', 'public, max-age=30'); response.json({ scope, games: publicGames, players: ranked }); } catch (error) { next(error); } });

  app.get('/api/matches/recent', async (request, response, next) => { try { const gameId = typeof request.query.game === 'string' ? request.query.game : undefined; const matches = await prisma.match.findMany({ where: { gameId }, orderBy: { endedAt: 'desc' }, take: 12, select: { id: true, gameId: true, playerCount: true, endedAt: true, resultJson: true, players: { orderBy: { placement: 'asc' }, select: { playerName: true, score: true, placement: true } } } }); response.json(matches.map((match) => ({ id: match.id, gameId: match.gameId, playerCount: match.playerCount, endedAt: match.endedAt, result: parseResult(match.resultJson), players: match.players }))); } catch (error) { next(error); } });
}
