import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';

interface Player { rank: number; id: string; displayName: string; avatarUrl: string | null; played: number; won: number; lost: number; draws: number; winRate: number; points: number }
interface Board { scope: string; games: Array<{ id: string; name: string }>; players: Player[] }
export function LeaderboardPage() {
  const [params, setParams] = useSearchParams(); const scope = params.get('game') ?? 'all';
  const [data, setData] = useState<Board | null>(null); const [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); setError(''); fetch(`/api/leaderboard?game=${encodeURIComponent(scope)}`, { signal: controller.signal }).then((r) => { if (!r.ok) throw new Error('Could not load the leaderboard.'); return r.json() as Promise<Board>; }).then(setData).catch((e: unknown) => { if (!(e instanceof DOMException && e.name === 'AbortError')) setError(e instanceof Error ? e.message : 'Could not load the leaderboard.'); }); return () => controller.abort(); }, [scope]);
  const tabs = [{ id: 'all', name: 'Global' }, ...(data?.games ?? [{ id: 'war', name: 'War' }, { id: 'mattis', name: 'Mattis' }, { id: 'chess', name: 'Chess' }])];
  return <main className="page-shell"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-amber-700">Players</p><h1 className="mt-2 text-5xl font-bold tracking-tight">Leaderboard</h1><p className="mt-4 max-w-2xl text-stone-600">Every registered player is listed. Wins earn three points and draws earn one; the global table combines all games.</p><nav className="mt-8 flex flex-wrap gap-2" aria-label="Leaderboard game">{tabs.map((tab) => <button className={scope === tab.id ? 'primary-button' : 'secondary-button'} key={tab.id} onClick={() => setParams(tab.id === 'all' ? {} : { game: tab.id })}>{tab.name}</button>)}</nav>{error && <p className="mt-8 text-red-700">{error}</p>}<div className="leaderboard-table mt-8"><div className="leaderboard-row leaderboard-head"><span>Rank</span><span>Player</span><span>Played</span><span>W / D / L</span><span>Win rate</span><span>Points</span></div>{data?.players.map((player) => <Link className="leaderboard-row" key={player.id} to={`/players/${player.id}`}><b>#{player.rank}</b><span className="flex min-w-0 items-center gap-3">{player.avatarUrl ? <img className="profile-avatar" src={player.avatarUrl} alt="" referrerPolicy="no-referrer" /> : <span className="profile-avatar profile-avatar-fallback">{player.displayName[0]}</span>}<b className="truncate">{player.displayName}</b></span><span>{player.played}</span><span>{player.won} / {player.draws} / {player.lost}</span><span>{player.winRate}%</span><b>{player.points}</b></Link>)}</div>{data && !data.players.length && <p className="mt-8 text-stone-500">No registered players yet.</p>}</main>;
}
